---
- name : XLD Infrastructure/ANSIBLE
  xldeploy.py:
    id: "Infrastructure/ANSIBLE"
    type: core.Directory
    endpoint: "{{ xld_endpoint}}"

- name : XLD Environments/ANSIBLE
  xldeploy.py:
    id: "Environments/ANSIBLE"
    type: core.Directory
    endpoint: "{{ xld_endpoint}}"

- name: XLD Define Host
  xldeploy.py:
    id: "Infrastructure/ANSIBLE/{{ ansible_fqdn }}.vm"
    type: overthere.SshHost
    endpoint: "{{ xld_endpoint}}"
    properties:
      os: UNIX
      address: "{{ ansible_fqdn }}"
      username: vagrant
      password: vagrant
      connectionType: INTERACTIVE_SUDO
      sudoUsername: root
      stagingDirectoryPath: /tmp

- name : XLD Define tomcat server
  xldeploy.py:
    id: "Infrastructure/ANSIBLE/{{ ansible_fqdn }}.vm/tomcat"
    type: tomcat.Server
    endpoint: "{{ xld_endpoint}}"
    properties:
      home: /var/lib/tomcat7
      startCommand: /etc/init.d/tomcat7 start
      stopCommand: /etc/init.d/tomcat7 stop
      startWaitTime: 10
      stopWaitTime: 0

- name : XLD Define tomcat virtual host
  xldeploy.py:
    id: "Infrastructure/ANSIBLE/{{ ansible_fqdn }}.vm/tomcat/tomcat.vh"
    type: tomcat.VirtualHost
    endpoint: "{{ xld_endpoint}}"

- name: XLD Define the smoke test runner
  xldeploy.py:
    id: "Infrastructure/ANSIBLE/{{ ansible_fqdn }}.vm/test-runner-{{ ansible_hostname }}"
    type: smoketest.Runner
    endpoint: "{{ xld_endpoint}}"

- name: XLD Define the dictionary for the node
  xldeploy.py:
    id: "Environments/ANSIBLE/{{ ansible_hostname }}.dict"
    type: udm.Dictionary
    endpoint: "{{ xld_endpoint}}"
    properties:
      entries: {'log.RootLevel':'ERROR', 'log.FilePath':'/tmp/null', 'tomcat.port':'8080','tomcat.DataSource.username':'scott','tomcat.DataSource.password':'tiger','TITLE':'ANSIBLE', 'tomcat.DataSource.driverClassName':'com.mysql.jdbc.Driver','tomcat.DataSource.url':'jdbc:mysql://localhost/petclinic', 'tomcat.DataSource.context':'petclinic','tests2.ExecutedHttpRequestTest.url':'http://localhost:8080/petclinic/index.jsp'}

- name: XLD Define the test environment
  xldeploy.py:
    id: Environments/ANSIBLE/ansible-tomcat-test
    type: udm.Environment
    endpoint: "{{ xld_endpoint}}"
    update_mode: add
    properties:
      members: ["Infrastructure/ANSIBLE/{{ ansible_fqdn }}.vm/tomcat/tomcat.vh", "Infrastructure/ANSIBLE/{{ ansible_fqdn }}.vm/tomcat","Infrastructure/ANSIBLE/{{ ansible_fqdn }}.vm", "Infrastructure/ANSIBLE/{{ ansible_fqdn }}.vm/test-runner-{{ ansible_hostname }}"]
      dictionaries: ["Environments/ANSIBLE/{{ ansible_hostname }}.dict"]


